# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DatingMessengers' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DatingMessengers
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'ObjectMapper'
  pod 'SwiftUtils'

  target 'DatingMessengersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DatingMessengersUITests' do
    # Pods for testing
  end

end
